<script>
    require(['jquery'], function($) {
        jQuery(document).ajaxComplete(function() {

            // if (jQuery('#checkout-loader').length == 0) {

            //      function AslowasCheckoutPayment() {

            //     var z = jQuery('.checkout-index-index .payment-method .credova-aslowas-payment .crdv-button').length

            //     if (z == 0) {
            //         CRDV.plugin.inject("credova-aslowas-payment");
            //     }
            //     if (z == 1) {
            //         jQuery(".crdv-button").show();
            //     }
            //     if (z > 1) {
            //         jQuery(".crdv-button").remove();
            //     }
            // }setTimeout(AslowasCheckoutPayment, 2000);

            // }


        })

    })
</script>