<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var PublicSquare\Payments\Block\Form $block */

$code = $block->escapeHtml($block->getMethodCode());
$ccType = $block->getInfoData('cc_type');
?>
<fieldset class="admin__fieldset payment-method"
          id="payment_form_<?= /* @noEscape */ $code ?>"
          style="display:none"
    >
    <div class="admin__field _required">
        <label class="label admin__field-label" for="<?= /* @noEscape */ $code ?>_cc_type" >
            <span><?= $block->escapeHtml(__('Credit Card')) ?></span>
        </label>
        <div class="admin__field-control control">
            <div id="publicsquare-elements-form"></div>
        </div>
    </div>

    <?php if ($block->isVaultEnabled()) : ?>
        <div class="field-tooltip-content">
            <input type="checkbox"
                   id="<?= /* @noEscape */ $code ?>_vault"
                   name="payment[is_active_payment_token_enabler]"
                   class="admin__control-checkbox"/>
            <label class="label admin__field-label" for="<?= /* @noEscape */ $code ?>_vault">
                <span><?= $block->escapeHtml(__('Save for later use.')) ?></span>
            </label>
        </div>
    <?php endif; ?>

    <input type="hidden" id="<?= /* @noEscape */ $code ?>_payment_method_nonce"
           name="payment[payment_method_nonce]"/>
    <input type="submit" name="Submit" style="display: none;">
</fieldset>