services:
  web:
    image: ghcr.io/alexcheng1982/docker-magento2:2.4.6-p5
    platform: linux/amd64
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
      opensearch:
        condition: service_healthy
    volumes:
      - magento-it-data:/var/www/html
      - ./PublicSquare:/var/www/html/app/code/PublicSquare
    env_file:
      - env/ci-stack.env
    networks:
      default:
        aliases:
          - magento.test
  db:
    image: mysql:8.0.35
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: magento
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
    ports:
      - "33306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "magento", "-pmagento" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    volumes:
      - db-it-data:/var/lib/mysql
  opensearch:
    image: markoshust/magento-opensearch:2.12-0
    env_file: env/opensearch.env
    environment:
      - "discovery.type=single-node"
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - "index.blocks.read_only_allow_delete"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsSL http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
  selenium:
    image: seleniarm/standalone-chromium:latest
    platform: linux/arm64
    shm_size: 2g
    ports:
      - "4444:4444"
      - "7900:7900"
volumes:
  magento-it-data:
  db-it-data:


