<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var PublicSquare\Payments\Block\Payment $block */

$code = $block->escapeHtml($block->getCode());

?>

<script nonce="<?= $block->getNonce() ?>">
    //<![CDATA[
    require(
        [
            'jquery',
            'publicsquare_payments'
        ], function($, publicsquare) {
            var config = <?= /* @noEscape */ $block->getPaymentConfig() ?>,
                form = $('#payment_form_<?= /* @noEscape */ $code ?>'),
                elementsFormSelector = '#publicsquare-elements-form',
                element = $(elementsFormSelector),
                payment;

            config.active = form.length > 0 && !form.is(':hidden');

            const observer = new IntersectionObserver(entries => {
                entries.forEach(entry => {
                    if (entry.isIntersecting && !element.children().length) {
                        requestAnimationFrame(() => {
                            publicsquare.initElements({
                                apiKey: config.pk || '',
                                selector: elementsFormSelector
                            }, () => { })
                        })
                    }
                });
            });

            const targetElement = element.get(0); 
            if (targetElement && publicsquare) {
                observer.observe(targetElement);
            }
        });
    //]]>
</script>
