<?php
$enabled = $block->isEnabled();
$form_action = $block->formAction();
?>

<?php if ($enabled): ?>
    <style>
        .psq-add-card {
            display: block;
            margin-top: 18px;

        }

        .psq-add-card__form--hidden {
            visibility: hidden;
        }

        .psq-add-card__form {
            display: block;
            padding: 4px;
            margin-top: 8px;
        }

    </style>
    <div class="psq-add-card">
        <button id="psq-cc-add-button" class="psq__cc-add-btn--enabled">Add Card</button>

        <div class="psq-add-card__form psq-add-card__form--hidden psq-form">
            <div class="psq-add-card__form__header">
                <p class="psq-form__cta">Enter new card information</p>
            </div>
            <?php echo $this->getChildHtml(); ?>
            <div class="psq-form__footer psq-form__actions">
                <button class="psq-form__button psq-form__button--primary action primary"
                        type="submit">
                    <span>Add Payment Method</span>
                </button>
                <button class="psq-form__button psq-form__button--cancel action"
                        type="button">
                    <span>Cancel</span>
                </button>
            </div>

            <form id="psq-save-to-vault" action="<?php echo $form_action; ?>" method="post">
                <input id="psq-new-card-id" type="hidden" name="card_id"/>
                <input id="psq-new-card-exp-year" name="exp_year" type="hidden"/>
                <input id="psq-new-card-exp-month" name="exp_month" type="hidden"/>
                <input id="psq-new-card-details" name="details" type="hidden"/>
            </form>
        </div>

        <hr>
    </div>
    <script type="text/javascript">
        require([
                    'jquery',
                    // 'mage/translate',
                    'Magento_Ui/js/model/messageList',
                    'PublicSquare_Payments/js/card-form-factory',
                ], function psqAddCCInit(
            $,
            // $t,
            messageList,
            cardFormFactory,
        ) {
            let formVisible = false;
            const cardInputCustomizationJSON = `<?php echo $escaper->escapeJs($block->getCardInputCustomizationJSON()); ?>`;
            const cardInputCustomization = JSON.parse(cardInputCustomizationJSON || '{}');
            const psqPublicKey = '<?php echo $block->getPublicKey(); ?>';
            const cardFormLayout = '<?php echo $this->getCardFormLayout(); ?>';
            let $modal;

            // cc elements bound by psq payments js
            let cardForm = null;

            async function save() {
                const $vaultForm = $('#psq-save-to-vault');
                try {

                    const card = await cardForm.createCard();
                    console.log('Card created. Posting to vault...');

                    // Update hidden form with information to save to vault
                    $('#psq-new-card-id').val(card.id);
                    $('#psq-new-card-exp-year').val(card.exp_year);
                    $('#psq-new-card-exp-month').val(card.exp_month);
                    $('#psq-new-card-details').val(
                        JSON.stringify({
                                           type: card.brand,
                                           maskedCC: card.last4,
                                           expirationDate: `${card.exp_month}/${card.exp_year}`,
                                       }),
                    );
                    if (!$vaultForm.valid()) {
                        console.warn('Found issues in form!');
                        messageList.addErrorMessage({message: 'Form information incorrect.'});
                        return;
                    }
                    // Submit to the Customer/Card controller.
                    $vaultForm.trigger('submit');
                } catch (err) {
                    console.error('Failed to save card!', err);
                    messageList.addErrorMessage({message: err.message || 'Form information incorrect.'});
                }

            }

            function closeForm() {
                // Remove class last
                $modal.addClass('psq-add-card__form--hidden');
            }

            async function openForm() {
                // Add class first
                if (!$modal) {
                    $modal = $('.psq-add-card__form');
                }
                $modal.removeClass('psq-add-card__form--hidden');

                if (!cardForm) {
                    console.debug('layout: %s cardFormBuilder:%o ', cardFormLayout, cardFormFactory);
                    cardForm = cardFormFactory({type: cardFormLayout});
                    console.debug('cardForm:%o', cardForm);
                    await cardForm.bind({psqPublicKey, cardInputCustomization});

                    $('.psq-form__button--cancel').click(() => {
                        formVisible = false;
                        closeForm();
                    });
                    $('.psq-form__button--primary').click(async () => {
                        await save();
                    });
                }
            }

            $('#psq-cc-add-button').click(async () => {
                console.log('PSQ: Add CC button clicked. formVisible was %s', formVisible);
                formVisible = !formVisible;
                if (formVisible) {
                    await openForm();
                } else {
                    await closeForm();
                }
            });
        });
    </script>
<?php endif; ?>
