<?php
$enabled = $block->isEnabled();
$form_action = $block->formAction();
?>

<?php if ($enabled): ?>
    <style type="text/css">
        .psq-add-card {
            display: block;
            margin-top: 8px;

        }

        .psq-add-card__form--hidden {
            visibility: hidden;
        }

        .psq-add-card__form {
            display: block;
            padding: 4px;
        }

        .psq-form__section {
            display: block;
            margin: 4px;
        }

        .psq-form__input {
            margin: 4px;
            display: inline-block;
        }

    </style>
    <div class="psq-add-card">
        <button id="psq-cc-add-button" class="psq__cc-add-btn--enabled">Add CC</button>

        <div class="psq-add-card__form psq-add-card__form--hidden psq-form">
            <p class="psq-form__cta">Enter new card information</p>
            <div class="psq-form__section">
                <label for="psq-form-cardholder-name">Cardholder Name</label>
                <input id="psq-form-cardholder-name"
                       style="psq-form__input"
                       type="text"
                       name="cardholder_name"
                       value="<?php echo $block->getCustomerName() ?>"/>

            </div>
            <div class="psq-form__section">
                <div id="psq-card-element"></div>

            </div>
            <div class="psq-form__actions">
                <button class="psq-form__button psq-form__button--primary action primary"
                        type="submit">
                    <span>Add Payment Method</span>
                </button>
                <button class="psq-form__button psq-form__button--cancel action"
                        type="button">
                    <span>Cancel</span>
                </button>
            </div>
            <form id="psq-save-to-vault" action="<?php echo $form_action; ?>" method="post">
                <input id="psq-new-card-id" type="hidden" name="card_id" />
            </form>
        </div>
    </div>
    <script type="text/javascript">
        require(['jquery', 'publicsquarejs'], function psqAddCCInit($, psqSdk) {
            let formVisible = false;
            const psqPubKey = '<?php echo $block->getPublicKey(); ?>';
            let psq;
            let $modal;

            // cc elements bound by psq payments js
            let $card;

            async function save() {
                const $form = $('#psq-save-to-vault');
                try {
                    if (!$card || !$card.metadata.valid) {
                        // TODO: ui notif
                        console.warn('Invalid card! %j', $card.metadata);
                        throw new Error('The card is invalid. Please check the card details and try again.');
                    }
                    const cardholderName = $('#psq-form-cardholder-name').val();
                    console.log('Creating new card for cardholder %s', cardholderName);
                    const card = psqSdk.cards.create({cardholder_name: cardholderName, card: $card});
                    $('#psq-new-card-id').val(card.id);
                    if (!$form.valid()) {
                        return;
                    }
                    $form.trigger('submit');
                } catch (err) {
                    console.error('Failed to save card!', err);
                } finally {
                    $form.unbind();
                }

            }

            function closeForm() {
                $('.psq-form__button--cancel').unbind();
                $('.psq-form__button--primary').unbind();


                // Remove class last
                $modal.addClass('psq-add-card__form--hidden');
            }

            async function openForm() {
                // Add class first
                if (!$modal) {
                    $modal = $('.psq-add-card__form');
                }
                $modal.removeClass('psq-add-card__form--hidden');

                if (!$card) {
                    psq = await psqSdk.init(psqPubKey);
                    $card = psq.createCardElement({});
                    $card.mount('#psq-card-element');
                }

                $('.psq-form__button--cancel').click(() => {
                    formVisible = false;
                    closeForm();
                });
                $('.psq-form__button--primary').click(async () => {
                    await save();
                });
            }

            $('#psq-cc-add-button').click(async () => {
                console.log('PSQ: Add CC button clicked. formVisible was %s', formVisible);
                formVisible = !formVisible;
                if (formVisible) {
                    await openForm();
                } else {
                    await closeForm();
                }
            });
        });
    </script>
<?php endif; ?>
