<div class="psq-form__content">
    <?php if ($this->showCardholderInput()): ?>
        <div class="psq-form__cell psq-form__cell--card-holder field required">
            <label for="psq-cardholder label" class="psq-form__label">Card Holder Name</label>
            <div class="psq-form__input psq-form__input--card-holder control">
                <input id="psq-cardholder" value="<?php echo $this->getCustomerName(); ?>">
            </div>
        </div>
    <?php endif; ?>


    <div class="psq-form__cell psq-form__cell--cc-types">
        <!-- TODO -->
    </div>
    <div class="psq-form__cell psq-form__cell--cc field required">
        <span class="psq-form__label">Credit Card Number</span>
        <div id="psq-card" class="psq-form__input psq-form__input--full-card control"></div>
    </div>
</div>

