<div class="psq-form__content">
    <?php if ($this->showCardholderInput()): ?>
        <div class="psq-form__cell psq-form__cell--card-holder field required">
            <label for="psq-cardholder label" class="psq-form__label">Card Holder Name</label>
            <div class="psq-form__input psq-form__input--card-holder control">
                <input id="psq-cardholder" value="<?php echo $this->getCustomerName(); ?>">
            </div>
        </div>
    <?php endif; ?>


    <div class="psq-form__cell psq-form__cell--cc-types">
        <!-- TODO -->
    </div>
    <div class="psq-form__cell psq-form__cell--cc field required">
        <span class="psq-form__label label">Credit Card Number</span>
        <div id="psq-card-num" class="psq-form__input psq-form__input--cc control"></div>
    </div>
    <div class="psq-form__cell psq-form__cell--exp field required">
        <span class="psq-form__label label">Expiration Date</span>
        <div id="psq-exp" class="psq-form__input psq-form__input--exp control"></div>
    </div>
    <div class="psq-form__cell psq-form__cell--cvc field number required">
        <span class="psq-form__label label">Card Verification Number (CVC)</span>
        <div id="psq-cvc" class="psq-form__input psq-form__input--cvc control"></div>
    </div>
</div>
