<?php
/** @var PublicSquare\Payments\Block\Frontend\Form $block */
$code = $escaper->escapeHtml($block->getMethodCode());
?>
<div class="psq-add-card__form psq-add-card__form--multi-ship psq-form">
    <div class="psq-add-card__form__header">
        <p class="psq-form__cta">Enter new card information</p>

    </div>
    <div class="psq-form__content" aria-label="Credit card form">

        <?php echo $this->getChildHtml(); ?>

        <?php if ($block->isVaultEnabled()): ?>
        <div class="psq-form__cell psq-form__cell--vault field number">
            <label for="psq-save-card" class="psq-form__label label">Save card for later</label>
            <input type="checkbox" id="psq-save-card" class="psq-form__input psq-form__input--vault control"></input>
        </div>
        <?php endif; ?>

        <div id="publicsquare_error_message" class="message error" role="alert" style="display:none"></div>

        <input type="hidden" id="<?= /* @noEscape */
        $code ?>_card_id" name="payment[additional_data][cardId]" required/>

        <input type="hidden" id="<?= /* @noEscape */
        $code ?>_idempotency_key" name="payment[additional_data][idempotencyKey]"/>

        <input type="hidden" id="<?= /* @noEscape */
        $code ?>_save_card" name="payment[additional_data][saveCard]"/>
    </div>
</div>


<script <?php if ($block->getCspNonceProvider()) echo ' nonce="' . $block->getCspNonceProvider()->generateNonce() . '" ' ?>>
    require([
                'jquery',
                'mage/translate',
                'Magento_Ui/js/model/messageList',
                'PublicSquare_Payments/js/card-form-factory',
                'PublicSquare_Payments/js/utils',
            ], function ($, $t, messageList, cardFormFactory, utils) {
        'use strict';
        const code = '<?= $code ?>';
        const psqPublicKey = '<?= $block->escapeJs($block->getPublicApiKey()) ?>';
        const cardFormLayout = '<?php echo $this->getCardFormLayout(); ?>';
        let cardForm = undefined;
        let idempotencyKey = utils.generateIdempotencyKey();
        const cardInputCustomizationJSON = `<?php echo $escaper->escapeJs($block->getCardInputCustomizationJSON()); ?>`;
        const cardInputCustomization = JSON.parse(cardInputCustomizationJSON || '{}');
        const vaultEnabled = <?php echo $escaper->escapeJs($block->isVaultEnabled()) ?>;


        function unmount() {
            $('#' + code + '_card_id').prop('disabled', true);
            $('#' + code + '_idempotency_key').prop('disabled', true);
            $('#' + code + '_save_card').prop('disabled', true);
        }

        function mount() {

            if (!cardForm) {
                cardForm = cardFormFactory({type: cardFormLayout});
                cardForm.bind({psqPublicKey, cardInputCustomization});
            }

            $('#' + code + '_card_id').prop('disabled', false);
            $('#' + code + '_idempotency_key').prop('disabled', false);
            $('#' + code + '_save_card').prop('disabled', false);
        }

        $(function () {
            // ensure idempotency key exists on load
            const $idem = $('#' + code + '_idempotency_key');

            mount();

            // Remount when user re-selects this method
            $(document).on('change', 'input[name="payment[method]"]', function () {
                if (this.value === 'publicsquare_payments' && this.checked) {
                    mount();
                } else {
                    unmount();
                }
            });

            // Adding this as there are some edge cases where going back doesn't successfully mount keeping it disabled
            /*$(document).on('click', '#' + code + '_cardholder_name', function (e) {
             const $el = $(this);
             if ($el.prop('disabled')) {
             // Remove disabled so it becomes enabled
             $el.prop('disabled', false);

             // Optionally: focus the element
             $el.focus();

             // Optionally: prevent default behaviour if any
             e.preventDefault();
             }
             });*/

            // Save card vault
            $(document).on('change', '#psq-save-card', function () {
                $('#' + code + '_save_card').val(this.checked || false);
            });

            // Intercept submit to tokenize and set hidden fields
            const $form = $("#multishipping-billing-form");
            $form.on('submit.publicsquare', async function (e) {

                // If method radios exist, only intercept when our method is selected
                const method = $('input[name="payment[method]"]:checked').val();
                if (method && method !== 'publicsquare_payments') { return; }

                e.preventDefault();
                try {

                    // Read cardholder name from input

                    let card = await cardForm.createCard();
                    if (!card) {
                        mount();
                        card = await cardForm.createCard();
                    }
                    if (!card) {
                        // cardForm will create it's own errors in the message list
                        return;
                    }
                    // regenerate idempotency key on each submit attempt
                    $idem.val(idempotencyKey);
                    if (card.id) {
                        $('#' + code + '_card_id').val(card.id);
                    }
                    $form.off('submit.publicsquare').trigger('submit');
                } catch (err) {
                    console.warn('psq: Failed to submit order.', err);
                    const msg = (
                                    err && err.message
                                ) || 'Error saving card.';
                    messageList.addErrorMessage({message: $t(msg)});
                }
            });
        });
    });
</script>