name: Test

on:
  push:
    # Trigger deployment to staging on commit to master
    #branches: [master]
    branches:
      - '*'
    # Trigger deployment when a commit is tagged
    tags:
      - '*'
jobs:
  test:
    runs-on: ubuntu-latest
    name: Build and test codeception tests
    services:
      db:
        image: docker://mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: magento
          MYSQL_DATABASE: magento
          MYSQL_USER: magento
          MYSQL_PASSWORD: magento
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      redis:
        # Docker Hub image
        image: redis
      opensearch:
        image: markoshust/magento-opensearch:2.12-0
        ports:
          - 9200:9200
          - 9300:9300
        options: -e="discovery.type=single-node" -e "plugins.security.disabled=true"  -e "plugins.security.ssl.http.enabled=false" --health-cmd="curl http://localhost:9200/_cluster/health" --health-interval=10s --health-timeout=5s --health-retries=10
        env:
          OPENSEARCH_HOST: opensearch
          OPENSEARCH_PORT: 9200
          # Prevent security patch conflicts with core M2 code
          DISABLE_SECURITY_PLUGIN: true
      rabbitmq:
        image: markoshust/magento-rabbitmq:3.12-0
        ports:
          - 15672:15672
          - 5672:5672
        env:
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: 5672
          RABBITMQ_MANAGEMENT_PORT: 15672
          RABBITMQ_DEFAULT_USER: magento
          RABBITMQ_DEFAULT_PASS: magento
          RABBITMQ_DEFAULT_VHOST: /
      mailcatcher:
        image: sj26/mailcatcher
        ports:
          - "1080:1080"
    permissions:
      id-token: write
      contents: write
    steps:
      - id: checkout
        name: Checkout code
        uses: actions/checkout@v4

      - name: Install
        run: make verify

      - name: Run Integration Tests
        run: