name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    name: Build and test codeception tests
    permissions:
      id-token: write
      contents: write
    steps:
      - name: create hosts entry for magento.test
        run: sudo echo "127.0.0.1 magento.test" | sudo tee -a /etc/hosts

      - id: checkout-code
        name: Checkout code
        uses: actions/checkout@v4

      - id: install-php
        name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: curl, mbstring, openssl, pdo, pdo_sqlite
          ini-values: memory_limit=-1, date.timezone='UTC'
          coverage: xdebug
          tools: composer:v2

      - id: composer-validate
        name: Validate composer.json and composer.lock
        run: composer validate

      - id: composer-install
        name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction --no-suggest

      - id: fix-permissions
        name: fix the file permissions
        run: bin/fixowns && bin/fixperms

      - id: make-verify
        name: Install Magento using make verify
        env:
          ADOBE_ACCESS_PUBLIC_KEY: ${{ secrets.ADOBE_ACCESS_PUBLIC_KEY }}
          ADOBE_ACCESS_PRIVATE_KEY: ${{ secrets.ADOBE_ACCESS_PRIVATE_KEY }}
        run: make verify

      - name: start selenium via docker cli
        run: docker run -d -p 4444:4444 -p 7900:7900 --shm-size="2g" selenium/standalone-chrome:latest

      - name: netstat to see services listening on ports
        run : sudo apt install net-tools && sudo netstat -lp

      - name: check selenium status
        run: echo $(curl -s "http://127.0.0.1:4444/wd/hub/status")

      - name: Wait for Selenium 127.0.0.1:4444
        run: |
          for i in {1..10}; do
            if curl -s "http://127.0.0.1:4444/wd/hub/status" | jq ".value.ready" | grep 'true'; then
              echo "Selenium is ready!"
              break
            fi
            echo $(curl -s "http://localhost:4444/wd/hub/status")
            echo "Waiting for Selenium to be ready..."
            sleep 3
          done

      - name: curl https://magento.test
        run: curl -k -I https://magento.test

      - id: run-tests
        name: Run Integration Tests
        run: php vendor/bin/codecept run Acceptance --debug


      - name: artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-output
          path: /home/runner/work/publicsquare-magento-payments-plugin/publicsquare-magento-payments-plugin/tests/_output/

